<a href="https://colab.research.google.com/github/Kanyakrishi/deep_learning/blob/main/LSTM_and_activation_fn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dense
from tensorflow.keras.layers import LeakyReLU
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
from numpy import array

In [17]:
X1 = list()
X2 = list()
X = list()
Y = list()

X1 = [(x+1)*2 for x in range(25)]
X2 = [(x+1)*3 for x in range(25)]
Y = [x1*x2 for x1,x2 in zip(X1,X2)]

print(Y)

ValueError: ignored

In [21]:
X = np.column_stack((X1, X2))
print(X)
X = array(X).reshape(25, 1, 2)
print(X)
model = Sequential()
model.add(LSTM(80, activation='relu', input_shape=(1, 2)))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mse')



[[ 2  3]
 [ 4  6]
 [ 6  9]
 [ 8 12]
 [10 15]
 [12 18]
 [14 21]
 [16 24]
 [18 27]
 [20 30]
 [22 33]
 [24 36]
 [26 39]
 [28 42]
 [30 45]
 [32 48]
 [34 51]
 [36 54]
 [38 57]
 [40 60]
 [42 63]
 [44 66]
 [46 69]
 [48 72]
 [50 75]]
[[[ 2  3]]

 [[ 4  6]]

 [[ 6  9]]

 [[ 8 12]]

 [[10 15]]

 [[12 18]]

 [[14 21]]

 [[16 24]]

 [[18 27]]

 [[20 30]]

 [[22 33]]

 [[24 36]]

 [[26 39]]

 [[28 42]]

 [[30 45]]

 [[32 48]]

 [[34 51]]

 [[36 54]]

 [[38 57]]

 [[40 60]]

 [[42 63]]

 [[44 66]]

 [[46 69]]

 [[48 72]]

 [[50 75]]]


In [ ]:
model.fit(X, np.array(Y), epochs=1000, validation_split=0.2, batch_size=1)

In [24]:
model2 = Sequential()
model2.add(LSTM(80, activation='tanh', input_shape=(1, 2)))
model2.add(Dense(10, activation='tanh'))
model2.add(Dense(1))
model2.compile(optimizer='adam', loss='mse')

In [25]:
test_input = array([55,80])
test_input = test_input.reshape((1, 1, 2))
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[3804.0615]]


In [ ]:
model2.fit(X, np.array(Y), epochs=1000, validation_split=0.2, batch_size=1)

In [28]:
test_input = array([55,80])
test_input = test_input.reshape((1, 1, 2))
test_output = model2.predict(test_input, verbose=0)
print(test_output) # worst

[[162.70186]]


In [ ]:
leaky_relu = LeakyReLU(alpha=0.01)
model3 = Sequential()
model3.add(LSTM(80, activation=leaky_relu, input_shape=(1, 2)))
model3.add(Dense(10, activation=leaky_relu))
model3.add(Dense(1))
model3.compile(optimizer='adam', loss='mse')
model3.fit(X, np.array(Y), epochs=1000, validation_split=0.2, batch_size=1)

In [36]:
test_input = array([55,80])
test_input = test_input.reshape((1, 1, 2))
test_output = model3.predict(test_input, verbose=0)
print(test_output) # best without using dense layers 

[[3743.45]]
